[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types =  ["py"]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "Poetry.lock", "manage.py"]
comment-token = "#"
language-servers = ["pyright", "ruff"]
indent = {tab-width = 4, unit = "    "}
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[language.formatter]
command = "ruff"
args = ["format", "-"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-lsp"]

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]
